<?php

namespace AppBundle\Repository;

/**
 * BuyingOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyingOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
