<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByLikeName($name)
    {
        dump($name);
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Customer c WHERE c.name LIKE :name ORDER BY c.name ASC'
            )
            ->setParameter('name', $name)
            ->getResult();
    }
}
