<?php

namespace AppBundle\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByLikeName($name, $role)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Employee e WHERE (e.name LIKE :name AND e INSTANCE OF :role) ORDER BY e.name ASC'
            )
            ->setParameter('name', $name)
            ->setParameter('role', $role)
            ->getResult();
    }
}
