<?php

namespace AppBundle\Repository;

/**
 * SellingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellingItemRepository extends \Doctrine\ORM\EntityRepository
{
}
